apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-build
  namespace: student-project
spec:
  steps:
    - args:
        - install
      command:
        - /usr/bin/mvn
      image: 'maven:3.6.0-jdk-11-slim'
      name: mvn-goals
      resources: {}
      workingDir: /workspace/output
  workspaces:
    - description: The workspace consisting of maven project.
      name: output
